version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.android.material:material
    versions:
    - 1.3.0
    - 1.3.0-rc01
    - 1.4.0-alpha01
